services:
  cart_database:
    image: postgres
    volumes:
      - cart_database:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - cart_db_network
    env_file:
      - .development.env
  cart_server:
    image: node:lts
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - cart_server_network
      - cart_db_network
    env_file:
      - .development.env
    depends_on:
      - cart_database
    command: "npm start"

volumes:
  cart_database:

networks:
  cart_server_network:
    internal: true
  cart_db_network:
    internal: true
