services:
  account_database:
    image: postgres
    volumes:
      - account_information:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - account_db_network
    env_file:
      - .development.env
  account_server:
    image: node:lts
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - account_server_network
      - account_db_network
    env_file:
      - .development.env
    depends_on:
      - account_database
    # command: "npm start"
    command: "npm run testandrun"

volumes:
  account_information:

networks:
  account_server_network:
    internal: true
  account_db_network:
    internal: true
