services:
  inventory_database:
    image: postgres
    volumes:
      - store_inventory:/var/lib/postgres/data
    networks:
      - inventory_db_network
    env_file:
      - .development.env
  inventory_server:
    image: node:lts
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - inventory_server_network
      - inventory_db_network
    env_file:
      - .development.env
    depends_on:
      - inventory_database
    command: "npm start"

volumes:
  store_inventory:

networks:
  inventory_server_network:
    internal: true
  inventory_db_network:
    internal: true
