services:
  ui_server:
    image: node:lts
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - frontend_network
    command: "npm start"

networks:
  frontend_network:
    internal: true
