services:
  order_database:
    image: postgres
    volumes:
      - order_database:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - order_db_network
    env_file:
      - .development.env
  order_server:
    image: node:lts
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - order_server_network
      - order_db_network
    env_file:
      - .development.env
    depends_on:
      - order_database
    command: "npm start"

volumes:
  order_database:

networks:
  order_server_network:
    internal: true
  order_db_network:
    internal: true